### ISSUE TITLE
Ordering of the login methods in inconsistent

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#1]
In the menu, the order goes GitHub, Twitter, Google. In the submit session page, it goes Twitter, Google, GitHub. Probably should be the same.

**Comment by alastairs** [comment]
I was going to try and fix this now if it was trivial, but I've looked in about four different files and haven't found the appropriate bit for the form displayed on the session submission page yet.

...I am using vim, on a Mac :smile:

FWIW, I deliberately re-ordered the login providers in the menu, in the hope that it might encourage people to use GitHub over Twitter or Google (and then Twitter over Google).  The order they were in before was the order we added support for them, which was as good as random order.

**Comment by adrianbanks** [comment]
These are added in `AuthConfig.cs`. I think we can just reorder them there to match the order in the menu (although we are then reliant on the ordering being kept in the auto provider code).

**Comment by alastairs** [comment]
Hmmm, seems to me like the order in which they are rendered should be separate from the order in which they are configured... I'll take a look over the weekend, and at #2 and #3 too.  There's a whole bunch of styling that needs doing on the authorised pages right now.

**Comment by adrianbanks** [comment]
Yes, I agree but for a quick fix we could just reorder them.

The page you get when you click submit a session is particularly horrible. I did some playing with it last night to make it nicer so already have some ideas.

**Comment by adrianbanks** [comment]
https://github.com/dddeastanglia/DDDEastAnglia/pull/13
