### ISSUE TITLE
The new session tweet button replaces the DDDEA site instead of opening in a new window

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#101]
We probably don't want to encourage people to navigate away from our site when tweeting about a session.

**Comment by alastairs** [comment]
That's odd: it worked as expected when I did my testing. Are you using Chrome, or another browser? (I tested in Chrome.)

**Comment by adrianbanks** [comment]
Chrome.

**Comment by alastairs** [comment]
The new tweet button is still just an `<a>` tag, so it should be simply a case of adding the `target` attribute with the appropriate value.

**Comment by alastairs** [comment]
The best I can do is `target="_blank"`, which opens in a new tab. More than that is going to require JavaScript to achieve. (I'm happy to do that if needed, just want to check whether this is "good enough".)

**Comment by adrianbanks** [comment]
That will work, yes.
