### ISSUE TITLE
GravatarUrl is spelled incorrectly in the UserProfile model

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#116]
It is spelled "GravitarUrl".

**Comment by alastairs** [comment]
This seems low priority in comparison with some of the other items. Could we push it back to [Voting Closes](https://github.com/dddeastanglia/DDDEastAnglia/issues?milestone=4)?

**Comment by adrianbanks** [comment]
Yes. I only put it in because it is a trivial change (unless it requires a database migration as well?). Should the voting closes milestone be closed?

**Comment by alastairs** [comment]
Yes, it will require a migration. Postponing to Agenda Announced (which I assume will be the next major DB migration).
