### ISSUE TITLE
Inconsistent heading sizes

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#12]
The welcome (home) page uses an `h1` for the title. All of the other pages use a `h2`, with the exception of the contact page.

I can live with the home page having a larger title, as that makes sense as the welcoming page, but the contact page should match the other.

**Comment by adrianbanks** [comment]
https://github.com/dddeastanglia/DDDEastAnglia/pull/15

**Comment by alastairs** [comment]
FIxed by #15.
