### ISSUE TITLE
Introduce a DI container

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#134]
It feels like we need one now that the application is getting bigger. I sure could have used one for the reset password change.

**Comment by ninjaferret** [comment]
I've got a branch almost ready for introducing Ninject

On 28 April 2013 22:30, Adrian Banks notifications@github.com wrote:

> It feels like we need one now that the application is getting bigger. I
> sure could have used one for the reset password change.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dddeastanglia/DDDEastAnglia/issues/134
> .

## 

Ian Johnson

**Comment by adrianbanks** [comment]
Ok, I won't start another then :wink:

**Comment by adrianbanks** [comment]
I've just looked at your branch. It might be worth using modules to group similar bindings together instead of having them all in the `RegisterServices` method.

**Comment by ninjaferret** [comment]
I've not used Ninject before was reading up a bit more on it before I did a
pull request and doing a fair bit of testing to make sure everything still
worked.

Modules would make things a lot cleaner, I'll stick a few in.

On 28 April 2013 22:42, Adrian Banks notifications@github.com wrote:

> I've just looked at your branch. It might be worth using modules to group
> similar bindings together instead of having them all in the
> RegisterServices method.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dddeastanglia/DDDEastAnglia/issues/134#issuecomment-17143335
> .

## 

Ian Johnson

**Comment by ninjaferret** [comment]
Take a look at my branch now and see what you think, I'll then get a pull
request in.

On 28 April 2013 22:46, Ian Johnson ij2030@gmail.com wrote:

> I've not used Ninject before was reading up a bit more on it before I did
> a pull request and doing a fair bit of testing to make sure everything
> still worked.
> 
> Modules would make things a lot cleaner, I'll stick a few in.
> 
> On 28 April 2013 22:42, Adrian Banks notifications@github.com wrote:
> 
> > I've just looked at your branch. It might be worth using modules to group
> > similar bindings together instead of having them all in the
> > RegisterServices method.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/dddeastanglia/DDDEastAnglia/issues/134#issuecomment-17143335
> > .
> 
> ## 
> 
> Ian Johnson

## 

Ian Johnson
