### ISSUE TITLE
Display the current commitish somewhere in the site.

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#135]
I would suggest in the admin area. This would enable us to see where the live site is in the log.

**Comment by alastairs** [comment]
The committish should be abbreviated to the first seven digits: there's no need to display the full thing as git itself will work happily with an abbreviated committish, and seven digits is the conventional abbreviated length used.

I've also enabled the AssemblyInfo patcher on TeamCity, so we can display a useful version number alongside the committish.

**Comment by alastairs** [comment]
IIRC @adrianbanks said he had some work along these lines already.

**Comment by alastairs** [comment]
When you do the committish bit specifically, please can you find a way other than relying on the working directory being a git repository. TeamCity is using server-side check-out and I'm not keen to switch that to agent-side checkout to support that kind of thing.

**Comment by adrianbanks** [comment]
To not require an agent side checkout, we can do it but only by configuring the build in Team City differently.

**Comment by alastairs** [comment]
No need for further configuration, you can just read the standard TeamCity environment variables at build time to bung it in (e.g., `BUILD_VCS_NUMBER`).

What this change will need in general is a deployment package to be built and deployed to Azure. It won't work with the current git deployment mechanism, ironically, as the site is deployed in an area outside of the site's git repository.

**Comment by adrianbanks** [comment]
Pull request #184.
