### ISSUE TITLE
Add the ability to promote users to administrators in the admin section

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#149]

**Comment by philpursglove** [comment]
Started some work on this this afternoon, I've got programmatic creation and deletion of roles done, will look at adding/removing users from roles over the weekend

**Comment by alastairs** [comment]
Nice :smile:

**Comment by alastairs** [comment]
How's this coming along, @philpursglove?

**Comment by philpursglove** [comment]
Should be in a position to create a pull request for this in the next day or so...
