### ISSUE TITLE
The tweet link logs you out of Twitter

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#16]
When you click the tweet link below a session, you are asked to log into twitter, even if you were already logged in.

**Comment by alastairs** [comment]
:scream:

**Comment by adrianbanks** [comment]
https://github.com/dddeastanglia/DDDEastAnglia/pull/17

**Comment by alastairs** [comment]
I wonder if this is why no-one has used this feature yet...

**Comment by adrianbanks** [comment]
Possibly. I intend on going through the whole sign-up & submit process with my ux hat on tomorrow. It will hopefully give it a thorough testing and flush out some bugs, but should also pick up on anything like this - it is possible, but hard or not worth the hassle.

**Comment by alastairs** [comment]
Fixed by #17.
