### ISSUE TITLE
You can still vote for a session after voting is closed if you know the url

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#180]
There is no checking in the controller to verify that it is valid to still vote.

**Comment by ninjaferret** [comment]
Have you actually looked at the RegisterVoteCommandHandler that actually
does the work? That should check if the conference is open for voting

On 25 May 2013 00:11, Adrian Banks notifications@github.com wrote:

> There is no checking in the controller to verify that it is valid to still
> vote.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dddeastanglia/DDDEastAnglia/issues/180
> .

## 

Ian Johnson

**Comment by adrianbanks** [comment]
Yes, you are correct - hadn't seen that as the classes are so decoupled :smile:
