### ISSUE TITLE
Sort sponsor logos by sponsor level?

### ISSUE THREAD

**Issue by alastairs** [dddeastanglia/DDDEastAnglia#23]
We should probably give greater prominence to the Platinum Sponsors, then the Gold, Silver and Bronze. We can do this by simply re-ordering the logos in the side bar.

On the Sponsors' page, I wonder if we want to group each set of logos under headings stating the level of support they have offered.

**Comment by adrianbanks** [comment]
On the sidebar, we should order them by how much they've given (monetary cost if given actual physical items). This amount is in the trello board.

On the sponsors' page, I think we should group them like you said.
