### ISSUE TITLE
Should we add a code of conduct to the website?

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#239]
e.g. http://confcodeofconduct.com

**Comment by SimonPStevens** [comment]
I personally find it pretty cheesy. People shouldn't have to be told to not be jerks. If there are people being inappropriate we just deal with them on the day.

(But if you want to, I have no real objection)

Simon

-----Original Message-----

**Comment by colinangusmackay** [comment]
Given there is now a code of conduct on the website, shouldn't this issue be closed off now?

https://www.dddeastanglia.com/Home/CodeOfConduct
