### ISSUE TITLE
Missing Sponsor Logos

### ISSUE THREAD

**Issue by alastairs** [dddeastanglia/DDDEastAnglia#24]
We are currently missing sponsor logos for:
- Microsoft (Platinum)
- Software Acumen (Platinum). It's possible Mark Dalgarno will be supplying the logo for one of his events, rather than the company itself.
- ...others?

I have chased Mark for a logo, and I hope to have something from his designer this week.  @philpursglove, please could you chase MS for theirs?

**Comment by alastairs** [comment]
Software East is now up on the production site.

**Comment by alastairs** [comment]
Also missing Gibraltar's logo and TekPub's logo. (TekPub's logo is added in #113.)

**Comment by adrianbanks** [comment]
The only logo outstanding is TechSmith. @philpursglove have you got one yet?

**Comment by philpursglove** [comment]
Have chased Betsy for one today...
