### ISSUE TITLE
Clicking the cross to dismiss the banner takes me to the GitHub repository.

### ISSUE THREAD

**Issue by alastairs** [dddeastanglia/DDDEastAnglia#249]
When a banner is displayed on the site (e.g. the staging site currently), clicking the cross in the banner should clear the banner. Instead, it takes me to the GitHub repository.

I expect this is because the "Fork me on GitHub" banner is overlaying the banner, and the transparency in the image is giving the impression that the banner can still be dismissed when it can't. 

Perhaps the banner should overlay the GitHub flag instead?

**Comment by adrianbanks** [comment]
Perhaps we could move the "fork me" banner to the bottom right?

**Comment by adrianbanks** [comment]
The "fork me" link has been removed.
