### ISSUE TITLE
Styling of speaker links is off

### ISSUE THREAD

**Issue by alastairs** [dddeastanglia/DDDEastAnglia#25]
Humph, don't know why this didn't show up in my testing :unamused: 

There is no padding between the link icon (i.e., the globe/bird) and the link text (i.e., the URL/Twitter user name).  It's also possible using the large icons is undesirable here, as they look slightly out-sized.

**Comment by alastairs** [comment]
![Padding Issue](https://f.cloud.github.com/assets/52957/349704/3811c3b6-9fe0-11e2-800e-54efda89b30d.png)

**Comment by adrianbanks** [comment]
It isn't doing that on my local copy. The icons are smaller and there is a space.

**Comment by adrianbanks** [comment]
This got fixed as part of the UX review changes.
