### ISSUE TITLE
Request for forgotten password results in error message

### ISSUE THREAD

**Issue by NathanGloyn** [dddeastanglia/DDDEastAnglia#290]
I had forgotten my password and attempted to reset it but after adding my email address and hitting reset I got an error message appear "Oops! That wasn't supposed to happen. "

**Comment by adrianbanks** [comment]
I've just manually sent you a password reset email. Could you let me know if you get it? Could you also try again on the site, as I've turned the detailed logging on? Thanks.

**Comment by NathanGloyn** [comment]
I've just been in a tried the site again, so hopefully you'll have some info in the logs.

Thanks for the reset password, that part worked but then I tried to log in and it says my username is wrong
