### ISSUE TITLE
Sessions Stats: Votes for the top 15 sessions should be configurable

### ISSUE THREAD

**Issue by alastairs** [dddeastanglia/DDDEastAnglia#292]
The purpose of these screens is to give us an idea of what our agenda will look like. Last year we only had 3 tracks x 5 slots = 15 sessions, but this year we will have 4 or 5 tracks x 5 slots = 20 or 25 sessions. This setting should be surfaced through the admin UI rather than through a config change or const in the code.

**Comment by adrianbanks** [comment]
Related to #289.

**Comment by alastairs** [comment]
Ok, I'll move my extra info into that issue and close this as a duplicate. Can you flesh out the other issue with more details of what else needs changing/updating, as it's not clear to me at the moment what else could be changed.
