### ISSUE TITLE
Add link to change profile picture on Gravatar

### ISSUE THREAD

**Issue by alastairs** [dddeastanglia/DDDEastAnglia#294]
We've had many (i.e., 3) people asking us how to update their profile picture - we should make this more discoverable.

**Comment by philpursglove** [comment]
Should we also use one of the other gravatar options than the grey bloke so we can differentiate people a bit?

**Comment by adrianbanks** [comment]
> Should we also use one of the other gravatar options than the grey bloke so we can differentiate people a bit?

Do we need to differentiate users this way? If people aren't aware of gravatar (which it seems some people aren't), then showing one of the default pictures (https://en.gravatar.com/site/implement/images/#default-image) doesn't really help users - they are all a bit weird apart from the one we use.

**Comment by adrianbanks** [comment]
https://github.com/dddeastanglia/DDDEastAnglia/pull/295
