### ISSUE TITLE
Hyperlink styles are inconsistent

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#3]
On the main and session pages, hyperlinks are underlined. On the other pages, they are only underlined when hovered over.

**Comment by alastairs** [comment]
...and on http://www.dddeastanglia.com/session, the colour of the link is wrong too, and it's italicised.

**Comment by adrianbanks** [comment]
https://github.com/dddeastanglia/DDDEastAnglia/pull/14

**Comment by alastairs** [comment]
Fixed by #14.
