### ISSUE TITLE
Show Sessions on the Sessions page

### ISSUE THREAD

**Issue by philpursglove** [dddeastanglia/DDDEastAnglia#31]
We agreed last night that we will show the submitted sessions on the Sessions index page.

**Comment by adrianbanks** [comment]
I've already done this as part of the work I'm doing at the moment. You can see the change in [this](https://github.com/adrianbanks/dddeastanglia/commit/9e66841c751fcea246f06d12a850a2de906c3c49#diff-9) commint.

**Comment by adrianbanks** [comment]
This is now merged into staging as part of #32.
