### ISSUE TITLE
Speakers page does not include in-page anchor tags to allow direct navigation to a speaker

### ISSUE THREAD

**Issue by JoelHT-Landmark** [dddeastanglia/DDDEastAnglia#33]
On the speakers page (http://www.dddeastanglia.com/Speaker), each speaker's entry is listed, but there is no way to navigate directly to the section of the page for a given speaker.

This page should include an in-page anchor tag so that the following URL would navigate directly to my entry (for example)

http://www.dddeastanglia.com/Speaker#Joel%20Hammond-Turner

Additionally, this page could show a "limited" bio (say 4 lines), and link to a profile page specific to the speaker - this would allow speakers to write long bios in their profile without the main speaker's page becoming ugly.

For example 

http://www.dddeastanglia.com/Speaker/12

would link to the full-page profile.

**Comment by adrianbanks** [comment]
There is now (currently only on the staging site, will be pushed to the live site soon) an anchor in the speakers' page for each speaker, allowing you to hyperlink directly to an individual speaker (e.g. http://dddeastanglia.com/Speaker#JoelHT). Each speaker also has their own page that shows their entire profile and their list of submitted sessions (e.g. http://dddeastanglia.com/Speaker/Details/23) - this page is already on the live site.
