### ISSUE TITLE
Session details page does not link to Speaker Bio

### ISSUE THREAD

**Issue by JoelHT-Landmark** [dddeastanglia/DDDEastAnglia#34]
The session details page (e.g. http://www.dddeastanglia.com/Session/Details/17) has a header giving the speaker's name and avatar, but doesn't provide a link to the speaker bio.

See also Issue #33

**Comment by adrianbanks** [comment]
This has now been done as part of https://github.com/dddeastanglia/DDDEastAnglia/pull/69.
