### ISSUE TITLE
Is it expected for an authenticated user to view other speakers and their submissions?

### ISSUE THREAD

**Issue by tugberkugurlu** [dddeastanglia/DDDEastAnglia#342]
I can view other speakers and their session submissions :smile: I am not sure that's an expected behavior or not :smile: 

There is already [a specific check on this](https://github.com/dddeastanglia/DDDEastAnglia/blob/442704f5874d361ad6a07b9e7eb5d2e367b3697b/DDDEastAnglia/Controllers/SpeakerController.cs#L91) to do the styling differently but I was expecting it to refuse if I try to view other people's sessions.

**Comment by adrianbanks** [comment]
Do you mean like [this](http://www.dddeastanglia.com/Speaker/Details/6495) and [this](http://www.dddeastanglia.com/Session/Details/8)? If so, then it is expected. When sessions are submitted, we show them publicly until voting starts.

If this isn't what you mean, could you give a specific example?

**Comment by tugberkugurlu** [comment]
Ah, cool! Yes, that's what I meant :smile:
