### ISSUE TITLE
Add Duration to the Admin Session Index view

### ISSUE THREAD

**Issue by philpursglove** [dddeastanglia/DDDEastAnglia#384]
Can we add a Duration column to the Admin Session Index. Would just help us in seeing at a glance how many 30 minute vs 60 minute sessions we have.

**Comment by philpursglove** [comment]
I'll do this at some point, haven't got time right now :-(

**Comment by adrianbanks** [comment]
I did add an indicator as to whether a session is a full or half session:

![image](https://user-images.githubusercontent.com/494732/60677740-4017a180-9e7a-11e9-8e2f-047bc6ded5f7.png)

**Comment by philpursglove** [comment]
@adrianbanks I completely missed that...
