### ISSUE TITLE
Create a page explaining the DDD process to new users

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#39]
Link to it from somewhere on the home page. 

Should explain the process the event will take, from session submission through to registration.

Should possibly also explain a bit of history about the DDD events.

**Comment by cerishaw** [comment]
For submitting a session it would be nice to know:
1) How long should they be?
2) What's on-topic for the event (or what's off topic if that's shorter)
3) What format should/could they take e.g. talks, demos, workshops
4) What level of expertise is required - can I just talk about a pet project or do I need to have some sort of platform to prove I know what I'm talking about

Might be useful to know how sessions get chosen as well (e.g. by voting - who gets to vote that sort of thing)

**Comment by alastairs** [comment]
I've made a start on this.
