### ISSUE TITLE
Prompt for confirmation when deleting a submitted session

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#40]
Currently, clicking the delete button just deletes the session.

**Comment by adrianbanks** [comment]
I've had a think about this and I don't think this is needed. When you click the delete link, it takes you to a confirmation page, so it would be a bit odd to have another confirmation on that page.

**Comment by alastairs** [comment]
It might be nicer if the confirmation was a modal dialog rather than a separate page, though.

**Comment by adrianbanks** [comment]
Possibly, but not worth the effort at the moment. There are more worthwhile things to spend time on, especially as we already have a confirmation for deletion.
