### ISSUE TITLE
The @ symbol doesn't line up with the text box for the twitter username on the profile page

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#43]

**Comment by adrianbanks** [comment]
Not sure how to style this to make it in the centre. It might be easier to remove it, and then deal with twitter handles that both start and don't start with a @ when we use them.

**Comment by alastairs** [comment]
You could put it inline in the field, like people do with the magnifying glass icon in search boxes.

In fact, the `.input-prepend` and `.add-on` classes are exactly what we want here; see "Extending form controls" on [this page](http://twitter.github.io/bootstrap/base-css.html#forms) of the Bootstrap docs.

**Comment by adrianbanks** [comment]
Fixed by #55.
