### ISSUE TITLE
Add a link to this issue tracker in the footer of the site

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#44]
As we have already had users reporting issues, let's encourage it.

**Comment by philpursglove** [comment]
Agreed - Joel H-T tweeted me yesterday with his feature requests, I asked him to log them on the repo...

----- Original Message -----

**Comment by alastairs** [comment]
I did a bit of a google around this topic earlier, and didn't come up with anything pre-made that we could use, sadly. However, perhaps with a bit of <del>plagiarism</del> inspiration from widgets like [UserVoice](https://www.uservoice.com/)'s and [Get Satisfaction](https://getsatisfaction.com/)'s, we could roll together a little JavaScript widget that posted back to the [GitHub REST API for Issues](http://developer.github.com/v3/issues/#create-an-issue).

**Comment by adrianbanks** [comment]
I was thinking to keep it simple and just put a hyperlink to the issues page with the text something like "Found a problem?". No need for anything complicated (or for that matter time-consuming to code).

**Comment by philpursglove** [comment]
I was thinking something similar...

----- Original Message -----

**Comment by adrianbanks** [comment]
Fixed by #48. I've just added a link to the issues page.
