### ISSUE TITLE
The tweet links are (sometimes) including the session url twice.

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#53]
I've had it do this intermittently. Haven't pinned it down yet as what the cause is. Sometimes the link is there twice, other times not. I _suspect_ that it is the Twitter js doing something, as when it appears twice, the tweet is selected up to the end of the first url, but the second url is not selected.

**Comment by alastairs** [comment]
This happens very reproducibly on Safari. I'll see if I can track it down further, but so far I've noticed this in the Developer Tools' log pane (logged at ERROR level):

```
Unsafe JavaScript attempt to access frame with URL http://dddeastanglia.com/Session from frame with URL http://platform.twitter.com/widgets/tweet_button.1366232305.html#_=1366578656847&count=none&id=twitter-widget-0&lang=en&original_referer=http%3A%2F%2Fdddeastanglia.com%2FSession&size=m&text=Check%20out%20this%20session%20for%20%23dddea%20-%20A%20Smorgasbord%20of%20Lightning%20Talks%20http%3A%2F%2Fdddeastanglia.com%2FSession%2FDetails%2F36&url=http%3A%2F%2Fdddeastanglia.com%2FSession%2FDetails%2F36. Domains, protocols and ports must match.
```

(Don't know how to make that wrap, sorry.)

**Comment by adrianbanks** [comment]
I think the easiest thing is to remove the javascript that modifies the tweet link and turns it to a button, and render a button with the correct url on it. If you have a page with lots of sessions on it, there is a noticeable delay on loading while the javascript renders the buttons.
