### ISSUE TITLE
SQL Exception (Cannot insert null) when registering a new local user

### ISSUE THREAD

**Issue by SimonPStevens** [dddeastanglia/DDDEastAnglia#63]
Not an issue on live - only on the voting branch.

**Comment by adrianbanks** [comment]
Do you have a stack trace, or know which field it is complaining about?

**Comment by SimonPStevens** [comment]
@adrianbanks It's already fixed (I've sent a pull request to Ian) - Sorry - I'm still trying to understand when github auto creates issues and when it doesn't.

**Comment by alastairs** [comment]
Already fixed, as per @SimonPStevens' comment.
