### ISSUE TITLE
There is no ability to reset a forgotten password

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#86]
I'm not sure whether this should be supported out of the box by the membership stuff, but there doesn't appear to be any way of doing it on the site.

**Comment by alastairs** [comment]
It is supported out of the box by the ASP.NET membership provider, yes.

**Comment by alastairs** [comment]
How are you progressing with this, @adrianbanks?

**Comment by adrianbanks** [comment]
Got it working barring the email part. I have one issue that I'm having trouble with other than that (although I can't remember what it is at the moment).

**Comment by alastairs** [comment]
Ok. Anything I can help with?

**Comment by adrianbanks** [comment]
Possibly, but I'll have to fire the branch up first to remember what the issue was.
