### ISSUE TITLE
Admin Area is b0rked.

### ISSUE THREAD

**Issue by alastairs** [dddeastanglia/DDDEastAnglia#96]
I tried visiting http://dddeastaging.azurewebsites.net/admin/adminhome as a newly-registered user, and got the standard unhelpful YSOD (Runtime Error, an error occurred, set customErrors to off, etc.).

If the user is not in the Admin role, a 404 Not Found response should be returned.

**Comment by alastairs** [comment]
This YSOD is also on production.

**Comment by adrianbanks** [comment]
I don't think that this is (currently) down to not being logged in as an admin. It seems to always throw an exception ("The controller for path '/admin/adminhome' was not found or does not implement IController.").

**Comment by alastairs** [comment]
This appears to be a routing issue as far as I can tell. `AdminHomeController` does implement `IController`, and so it must be that it can't be found.

**Comment by ninjaferret** [comment]
I think I know why, moving the banner to a controller action in the
_Layout.cshtml ties us to the standard controllers.

When rendering the Admin area it can't find the controller because it can't
look outside it's own namespace?

Maybe a simple solution is to change the default layout to something
simpler for the administrator pages?

On 22 April 2013 14:21, Alastair Smith notifications@github.com wrote:

> This appears to be a routing issue as far as I can tell.
> AdminHomeController does implement IController, and so it must be that it
> can't be found.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dddeastanglia/DDDEastAnglia/issues/96#issuecomment-16785239
> .

## 

Ian Johnson

**Comment by adrianbanks** [comment]
Yes, that might make it easier. Currently, most of the links in the layout are broken due to them being in the admin folder. Removing them (and having a "back to main site" link?) would solve this as well.

**Comment by ninjaferret** [comment]
I think for any urls/actions etc we would probably specify the area in the
route value objects

Html.ActionLink("Display Text", "Action", "Banner", new { area = "" }, null
);

However, for the admin stuff we don't need a lot of the general bumpfh that
the proles need, like the sponsors and the timeline etc, might be better to
have a set of admin related headers and as you say a main "back to site"
link

On 22 April 2013 15:12, Adrian Banks notifications@github.com wrote:

> Yes, that might make it easier. Currently, most of the links in the layout
> are broken due to them being in the admin folder. Removing them (and having
> a "back to main site" link?) would solve this as well.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dddeastanglia/DDDEastAnglia/issues/96#issuecomment-16789825
> .

## 

Ian Johnson

**Comment by alastairs** [comment]
Good thinking. I should be able to take a look at that a bit later.

**Comment by alastairs** [comment]
I think a separate Layout.cshtml file would make most sense. We can then style it to suit our needs, rather than being constrained by the existing visual framework.
